USE mysql;

DROP DATABASE IF EXISTS test;
DELETE FROM mysql.user WHERE User='';
CREATE DATABASE IF NOT EXISTS inception;
FLUSH PRIVILEGES;
ALTER USER 'root'@'localhost' IDENTIFIED BY 'MYSQL_ROOT_PASSWORD';
CREATE OR REPLACE USER wordpress@'%' IDENTIFIED BY 'MYSQL_PASSWORD';
CREATE OR REPLACE USER agrotzsc@'%' IDENTIFIED BY 'MYSQL_PASSWORD';
GRANT ALL PRIVILEGES ON inception.*  TO 'wordpress'@'%';
GRANT ALL PRIVILEGES ON inception.*  TO agrotzsc@'%';
FLUSH PRIVILEGES;